[project]
name = "pretix_csob"
dynamic = ["version"]
description = "ČSOB payment gateway plugin for pretix"
readme = "README.md"
license = { file = "LICENSE" }
keywords = ["pretix"]
authors = [
    { name = "Nick Settler" },
]
maintainers = [
    { name = "Jan Pohanka" },
]

dependencies = [
    "pretix>=2026.6.0.dev0",
    "pycryptodome==3.23.*",
    "requests",
]

[project.entry-points."pretix.plugin"]
pretix_csob = "pretix_csob:PretixPluginMeta"

[project.entry-points."distutils.commands"]
build = "pretix_plugin_build.build:CustomBuild"

[build-system]
requires = [
    "setuptools",
    "pretix-plugin-build",
]

[tool.setuptools]
include-package-data = true

[tool.setuptools.dynamic]
version = { attr = "pretix_csob.__version__" }

[tool.setuptools.packages.find]
include = ["pretix*"]
namespaces = false

[tool.black]
line-length = 100
